version: "3"

services:
    app:
        build:
            context: ./docker/app/
            dockerfile: ./Dockerfile
        tty: true
        volumes:
            - ./img:/Switch-Fightstick/img
            - ./hex:/Switch-Fightstick/mnt